local M = {}

function M.new(cwd, lane)
	return {
		assistant_text = nil,
		assistant_thinking = {},
		message_text = nil,
		model_label = nil,
		model_profile = nil,
		model_profile_override = false,
		chunk_lines = {},
		chunk_path = nil,
		chat_read_only = false,
		comment_buffers = {},
		compose_buf = nil,
		cwd = cwd,
		highlight_buf = nil,
		job_id = nil,
		lane = lane,
		last_summary = nil,
		last_touched_file = nil,
		last_error = nil,
		last_user_message = nil,
		log_buf = nil,
		pending_request = nil,
		progress = nil,
		active_flow_card_id = nil,
		flow_cards = {},
		flow_card_seq = 0,
		q_answer_buf = nil,
		q_answer_card_id = nil,
		q_answer_done = false,
		q_answer_prompt = nil,
		q_answer_text = nil,
		q_answer_win = nil,
		recent_files = {},
		request_seq = 0,
		review = nil,
		review_acceptances = {},
		review_buf = nil,
		review_win = nil,
		search_history = {},
		status = {},
		status_buf = nil,
		stderr_tail = "",
		stdout_tail = "",
		tool_args = {},
		tool_marks = {},
		tool_paths = {},
		widget = {},
	}
end

return M
